import { useEffect, useState } from 'react';
import { Check, ChevronLeft, CircleAlert, Link2Off, LoaderCircle } from 'lucide-react';
import { projectFetch } from '../project-auth';
import './project-settings.css';

const emptyState = { plane: { provider: 'plane', connected: false }, discord: { provider: 'discord', connected: false } };
async function apiJson(url, options) { const response = await projectFetch(url, options); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.error || `Request failed (${response.status})`); return payload; }
function StatusBadge({ connected }) { return <span className={`project-integration-status ${connected ? 'connected' : 'disconnected'}`}>{connected ? <Check size={13} /> : <CircleAlert size={13} />}{connected ? 'Connected' : 'Not connected'}</span>; }
function Busy({ children }) { return <><LoaderCircle size={14} className="project-settings-spinner" />{children}</>; }

export default function ProjectSettings({ onClose }) {
  const [integrations, setIntegrations] = useState(emptyState); const [guilds, setGuilds] = useState([]); const [channels, setChannels] = useState([]); const [guildId, setGuildId] = useState(''); const [channelId, setChannelId] = useState('');
  const [busy, setBusy] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const reload = () => apiJson('/api/chat/integrations').then((result) => { const next = Object.fromEntries((result.integrations || []).map((item) => [item.provider, item])); setIntegrations({ ...emptyState, ...next }); return next; });
  useEffect(() => { const params = new URLSearchParams(window.location.search); if (params.get('status') === 'connected') setMessage(`${params.get('integration') === 'discord' ? 'Discord' : 'Plane'} account connected.`); if (params.get('status') === 'error') setError('The provider authorization could not be completed.'); reload().catch((loadError) => setError(loadError.message)); }, []);
  useEffect(() => { if (!integrations.discord.connected || integrations.discord.guildId) return; apiJson('/api/integrations/discord/guilds').then((result) => setGuilds(result || [])).catch((loadError) => setError(loadError.message)); }, [integrations.discord.connected, integrations.discord.guildId]);
  useEffect(() => { if (!guildId) { setChannels([]); return; } apiJson(`/api/integrations/discord/guilds/${guildId}/channels`).then((result) => setChannels(result || [])).catch((loadError) => setError(loadError.message)); }, [guildId]);
  const startOAuth = async (provider) => { setBusy(provider); setError(''); try { const path = provider === 'plane' ? `/api/integrations/${provider}/oauth/start` : `/api/integrations/${provider}/connect`; const response = await fetch(path, { credentials: 'include', redirect: 'manual' }); if (response.type === 'opaqueredirect' || (response.status >= 300 && response.status < 400)) { const location = response.headers.get('location'); if (location) window.location.assign(location); else window.location.assign(path); return; } const payload = await response.json().catch(() => null); throw new Error(payload?.action || payload?.error || 'Provider authorization is unavailable.'); } catch (startError) { setError(startError.message); setBusy(''); } };
  const disconnect = async (provider) => { if (!window.confirm(`Disconnect ${provider === 'plane' ? 'Plane' : 'Discord'}?`)) return; setBusy(`disconnect-${provider}`); setError(''); try { await apiJson(`/api/integrations/${provider}`, { method: 'DELETE' }); await reload(); setMessage(`${provider === 'plane' ? 'Plane' : 'Discord'} disconnected.`); } catch (disconnectError) { setError(disconnectError.message); } finally { setBusy(''); } };
  const saveDestination = async (event) => { event.preventDefault(); setBusy('destination'); setError(''); try { const result = await apiJson('/api/integrations/discord/destination', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ guildId, channelId }) }); setIntegrations((current) => ({ ...current, discord: result.integration })); setMessage('Discord destination saved.'); } catch (saveError) { setError(saveError.message); } finally { setBusy(''); } };
  const plane = integrations.plane; const discord = integrations.discord;
  return <div className="project-settings-overlay" role="dialog" aria-modal="true" aria-labelledby="project-settings-title"><div className="project-settings-panel">
    <header className="project-settings-header"><button type="button" className="project-settings-back" onClick={onClose}><ChevronLeft size={18} /> Back</button><div><span className="eyebrow">ACCOUNT</span><h1 id="project-settings-title">Integration settings</h1></div></header>
    <p className="project-settings-intro">Connect provider accounts securely. Authorization happens with the provider; secrets stay on the backend.</p>
    {message && <div className="project-settings-notice success" role="status"><Check size={15} />{message}</div>}{error && <div className="project-settings-notice error" role="alert"><CircleAlert size={15} />{error}</div>}
    <section className="project-integration-card"><div className="project-integration-card-header"><div><h2>Plane</h2><p>Connect your Plane workspace.</p></div><StatusBadge connected={plane.connected} /></div>
      {plane.connected ? <><div className="project-integration-meta">{plane.metadata?.workspaceName ? `Workspace: ${plane.metadata.workspaceName}` : 'Plane account connected'}{plane.metadata?.accountName ? ` · Account: ${plane.metadata.accountName}` : ''}<br />Authentication method: {plane.credentialType === 'pat' ? 'Personal Access Token' : 'OAuth'}</div><div className="project-settings-actions"><button type="button" disabled={busy === 'plane'} onClick={() => startOAuth('plane')}>{busy === 'plane' ? <Busy>Authorizing…</Busy> : 'Reconnect'}</button><button type="button" className="secondary" disabled={busy === 'disconnect-plane'} onClick={() => disconnect('plane')}><Link2Off size={14} /> Disconnect</button></div></> : <><div className="project-settings-actions"><button type="button" disabled={busy === 'plane'} onClick={() => startOAuth('plane')}>{busy === 'plane' ? <Busy>Authorizing…</Busy> : 'Connect Plane'}</button></div><details className="project-settings-advanced"><summary>Advanced setup</summary><form onSubmit={async (event) => { event.preventDefault(); const token = event.currentTarget.token.value.trim(); if (!token) return; setBusy('plane-pat'); try { const result = await apiJson('/api/integrations/plane/connect', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ token }) }); setIntegrations((current) => ({ ...current, plane: result.integration })); event.currentTarget.reset(); setMessage('Plane connected with a Personal Access Token.'); } catch (e) { setError(e.message); } finally { setBusy(''); } }} className="project-settings-form"><label>Personal Access Token<input name="token" type="password" autoComplete="off" placeholder="Only use if OAuth is unavailable" /></label><button type="submit" disabled={busy === 'plane-pat'}>{busy === 'plane-pat' ? <Busy>Validating…</Busy> : 'Connect with Personal Access Token'}</button></form></details></>}
    </section>
    <section className="project-integration-card"><div className="project-integration-card-header"><div><h2>Discord</h2><p>Connect Discord to receive project notifications.</p></div><StatusBadge connected={discord.connected} /></div>
      {!discord.connected ? <div className="project-settings-actions"><button type="button" disabled={busy === 'discord'} onClick={() => startOAuth('discord')}>{busy === 'discord' ? <Busy>Authorizing…</Busy> : 'Connect Discord'}</button></div> : discord.guildId && discord.channelId ? <><div className="project-integration-meta">Server: {discord.metadata?.guildName || 'Selected server'} · Channel: #{discord.metadata?.channelName || 'Selected channel'}</div><div className="project-settings-actions"><button type="button" onClick={() => { setGuildId(''); setChannelId(''); setIntegrations((current) => ({ ...current, discord: { ...current.discord, guildId: null, channelId: null } })); }}>Change destination</button><button type="button" className="secondary" disabled={busy === 'disconnect-discord'} onClick={() => disconnect('discord')}><Link2Off size={14} /> Disconnect</button></div></> : <form onSubmit={saveDestination} className="project-settings-form"><label>Server<select value={guildId} onChange={(event) => { setGuildId(event.target.value); setChannelId(''); }}><option value="">Select a server</option>{guilds.map((guild) => <option key={guild.id} value={guild.id}>{guild.name}</option>)}</select></label><label>Notification channel<select value={channelId} onChange={(event) => setChannelId(event.target.value)} disabled={!guildId}><option value="">Select a channel</option>{channels.map((channel) => <option key={channel.id} value={channel.id}>#{channel.name}</option>)}</select></label><button type="submit" disabled={busy === 'destination' || !guildId || !channelId}>{busy === 'destination' ? <Busy>Saving…</Busy> : 'Save destination'}</button><button type="button" className="secondary" onClick={() => disconnect('discord')}>Disconnect</button></form>}
    </section>
  </div></div>;
}
