import { useEffect, useRef, useState } from 'react';
import { Check, ChevronLeft, CircleAlert, Link2Off, LoaderCircle } from 'lucide-react';
import { projectFetch } from '../project-auth';
import './project-settings.css';

const emptyState = { plane: { provider: 'plane', connected: false, status: 'disconnected' }, discord: { provider: 'discord', connected: false, status: 'disconnected' } };
const planeStatus = (plane) => plane?.status || (plane?.connected ? (plane.workspaceSlug && plane.metadata?.defaultProjectId ? 'ready' : 'scopeIncomplete') : 'disconnected');
const planeStatusCopy = { ready: 'Ready', scopeIncomplete: 'Scope incomplete', connected: 'Connected', disconnected: 'Not connected' };
async function apiJson(url, options) { const response = await projectFetch(url, options); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.error || `Request failed (${response.status})`); return payload; }
function StatusBadge({ integration, provider }) { const status = provider === 'plane' ? planeStatus(integration) : (integration.connected ? 'connected' : 'disconnected'); const connected = status === 'ready' || status === 'connected'; return <span className={`project-integration-status ${connected ? 'connected' : 'disconnected'}`}>{connected ? <Check size={13} /> : <CircleAlert size={13} />}{provider === 'plane' ? planeStatusCopy[status] : connected ? 'Connected' : 'Not connected'}</span>; }
function Busy({ children }) { return <><LoaderCircle size={14} className="project-settings-spinner" />{children}</>; }
export function navigateToOAuthStart(provider, inFlight, navigate) {
  if (inFlight.current) return false;
  inFlight.current = true;
  navigate(provider === 'plane' ? `/api/integrations/${provider}/oauth/start` : `/api/integrations/${provider}/connect`);
  return true;
}

export default function ProjectSettings({ onClose }) {
  const [integrations, setIntegrations] = useState(emptyState);
  const [guilds, setGuilds] = useState([]); const [channels, setChannels] = useState([]); const [guildId, setGuildId] = useState(''); const [channelId, setChannelId] = useState('');
  const [planeWorkspace, setPlaneWorkspace] = useState(''); const [planeProjects, setPlaneProjects] = useState([]); const [planeProjectId, setPlaneProjectId] = useState(''); const [planeDirty, setPlaneDirty] = useState(false);
  const [hrmOptions, setHrmOptions] = useState(null); const [chatUserId, setChatUserId] = useState(''); const [hrmEmployeeId, setHrmEmployeeId] = useState('');
  const [busy, setBusy] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const oauthStartInFlight = useRef(false);
  const reload = () => apiJson('/api/chat/integrations').then((result) => { const next = Object.fromEntries((result.integrations || []).map((item) => [item.provider, item])); setIntegrations({ ...emptyState, ...next }); return next; });

  async function loadPlaneProjects({ workspaceSlug = planeWorkspace.trim(), selectedProjectId = '', announce = true } = {}) {
    if (!workspaceSlug) { setError('Enter a Plane workspace slug before loading projects.'); return; }
    setBusy('plane-projects'); if (announce) setMessage(''); setError('');
    try {
      const projects = (await apiJson(`/api/integrations/plane/projects?workspaceSlug=${encodeURIComponent(workspaceSlug)}`)).projects || [];
      setPlaneProjects(projects);
      setPlaneProjectId(projects.some((project) => project.id === selectedProjectId) ? selectedProjectId : '');
      if (announce) setMessage('Workspace verified. Select a project and save Plane scope to finish setup.');
    } catch (loadError) {
      setPlaneProjects([]); setPlaneProjectId('');
      setError(`Could not verify workspace slug "${workspaceSlug}". ${loadError.message}`);
    } finally { setBusy(''); }
  }

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    if (params.get('status') === 'connected') setMessage(`${params.get('integration') === 'discord' ? 'Discord' : 'Plane'} account connected.`);
    if (params.get('status') === 'error') setError('The provider authorization could not be completed.');
    reload().catch((loadError) => setError(loadError.message));
  }, []);
  useEffect(() => { if (!integrations.discord.connected || integrations.discord.guildId) return; apiJson('/api/integrations/discord/guilds').then((result) => setGuilds(result || [])).catch((loadError) => setError(loadError.message)); }, [integrations.discord.connected, integrations.discord.guildId]);
  useEffect(() => { if (!guildId) { setChannels([]); return; } apiJson(`/api/integrations/discord/guilds/${guildId}/channels`).then((result) => setChannels(result || [])).catch((loadError) => setError(loadError.message)); }, [guildId]);
  useEffect(() => {
    const savedWorkspace = integrations.plane.workspaceSlug || '';
    const savedProjectId = integrations.plane.metadata?.defaultProjectId || '';
    if (!integrations.plane.connected) { setPlaneWorkspace(''); setPlaneProjects([]); setPlaneProjectId(''); setPlaneDirty(false); return; }
    setPlaneWorkspace(savedWorkspace); setPlaneProjectId(savedProjectId); setPlaneDirty(false);
    if (savedWorkspace) loadPlaneProjects({ workspaceSlug: savedWorkspace, selectedProjectId: savedProjectId, announce: false });
  }, [integrations.plane.connected, integrations.plane.workspaceSlug, integrations.plane.metadata?.defaultProjectId]);

  const startOAuth = (provider) => { if (!navigateToOAuthStart(provider, oauthStartInFlight, window.location.assign.bind(window.location))) return; setBusy(provider); setError(''); };
  const disconnect = async (provider) => { if (!window.confirm(`Disconnect ${provider === 'plane' ? 'Plane' : 'Discord'}?`)) return; setBusy(`disconnect-${provider}`); setError(''); try { await apiJson(`/api/integrations/${provider}`, { method: 'DELETE' }); await reload(); setMessage(`${provider === 'plane' ? 'Plane' : 'Discord'} disconnected.`); } catch (disconnectError) { setError(disconnectError.message); } finally { setBusy(''); } };
  const saveDestination = async (event) => { event.preventDefault(); setBusy('destination'); setError(''); try { const result = await apiJson('/api/integrations/discord/destination', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ guildId, channelId }) }); setIntegrations((current) => ({ ...current, discord: result.integration })); setMessage('Discord destination saved.'); } catch (saveError) { setError(saveError.message); } finally { setBusy(''); } };
  const savePlaneScope = async (event) => { event.preventDefault(); const workspaceSlug = planeWorkspace.trim(); if (!workspaceSlug || !planeProjectId) return; setBusy('plane-scope'); setError(''); try { await apiJson('/api/integrations/plane/scope', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ workspaceSlug, projectId: planeProjectId }) }); await reload(); setPlaneDirty(false); setMessage('Plane workspace and project scope saved. Plane is ready.'); } catch (saveError) { setError(saveError.message); } finally { setBusy(''); } };
  const loadHrmOptions = async () => { setBusy('hrm-options'); setError(''); try { const options = await apiJson('/api/hrm/identity-link-options'); setHrmOptions(options); setChatUserId(''); setHrmEmployeeId(''); } catch (loadError) { setError(loadError.message); } finally { setBusy(''); } };
  const selectedLink = hrmOptions?.links?.find((link) => link.userId === chatUserId) || null;
  const saveHrmLink = async (event) => { event.preventDefault(); if (!chatUserId || !hrmEmployeeId) return; setBusy('hrm-link'); setError(''); try { await apiJson(`/api/hrm/identity-links/${encodeURIComponent(chatUserId)}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ employeeId: hrmEmployeeId }) }); const options = await apiJson('/api/hrm/identity-link-options'); setHrmOptions(options); setMessage(selectedLink ? 'HRM identity mapping replaced.' : 'HRM identity linked.'); } catch (saveError) { setError(saveError.message); } finally { setBusy(''); } };
  const disconnectHrmLink = async () => { if (!selectedLink || !window.confirm('Disconnect this HRM identity mapping?')) return; setBusy('hrm-unlink'); setError(''); try { await apiJson(`/api/hrm/identity-links/${encodeURIComponent(chatUserId)}`, { method: 'DELETE' }); const options = await apiJson('/api/hrm/identity-link-options'); setHrmOptions(options); setHrmEmployeeId(''); setMessage('HRM identity mapping disconnected.'); } catch (unlinkError) { setError(unlinkError.message); } finally { setBusy(''); } };
  const close = () => { if (planeDirty && !window.confirm('You have unsaved Plane scope changes. Close Settings without saving?')) return; onClose(); };
  const plane = integrations.plane; const discord = integrations.discord; const savePlaneDisabled = busy === 'plane-scope' || !planeWorkspace.trim() || !planeProjects.some((project) => project.id === planeProjectId);
  return <div className="project-settings-overlay" role="dialog" aria-modal="true" aria-labelledby="project-settings-title"><div className="project-settings-panel">
    <header className="project-settings-header"><button type="button" className="project-settings-back" onClick={close}><ChevronLeft size={18} /> Back</button><div><span className="eyebrow">ACCOUNT</span><h1 id="project-settings-title">Integration settings</h1></div></header>
    <p className="project-settings-intro">Connect provider accounts securely. Authorization happens with the provider; secrets stay on the backend.</p>
    {message && <div className="project-settings-notice success" role="status"><Check size={15} />{message}</div>}{error && <div className="project-settings-notice error" role="alert"><CircleAlert size={15} />{error}</div>}
    <section className="project-integration-card"><div className="project-integration-card-header"><div><h2>Plane</h2><p>Connect your Plane account, then choose the workspace and default project used by work-management tools.</p></div><StatusBadge integration={plane} provider="plane" /></div>
      {plane.connected && <form onSubmit={savePlaneScope} className="project-settings-form"><label>Workspace slug<input value={planeWorkspace} onChange={(event) => { setPlaneWorkspace(event.target.value); setPlaneProjects([]); setPlaneProjectId(''); setPlaneDirty(true); setMessage(''); setError(''); }} placeholder="your-workspace" /></label><button type="button" disabled={busy === 'plane-projects' || !planeWorkspace.trim()} onClick={() => { setPlaneDirty(true); loadPlaneProjects(); }}>{busy === 'plane-projects' ? <Busy>Loading projects…</Busy> : 'Load projects'}</button><label>Default project<select value={planeProjectId} onChange={(event) => { setPlaneProjectId(event.target.value); setPlaneDirty(true); }} disabled={!planeProjects.length}><option value="">Select a project</option>{planeProjects.map((project) => <option key={project.id} value={project.id}>{project.name || project.id}</option>)}</select></label><button type="submit" disabled={savePlaneDisabled}>{busy === 'plane-scope' ? <Busy>Saving…</Busy> : 'Save Plane scope'}</button></form>}
      {plane.connected ? <><div className="project-integration-meta">{planeStatus(plane) === 'ready' ? 'Plane is ready for work-management tools.' : 'Plane is connected, but workspace/project scope is not configured yet.'}{plane.metadata?.workspaceName ? ` Workspace: ${plane.metadata.workspaceName}` : ''}{plane.metadata?.accountName ? ` · Account: ${plane.metadata.accountName}` : ''}<br />Authentication method: {plane.credentialType === 'pat' ? 'Personal Access Token' : 'OAuth'}</div><div className="project-settings-actions"><button type="button" disabled={busy === 'plane'} onClick={() => startOAuth('plane')}>{busy === 'plane' ? <Busy>Authorizing…</Busy> : 'Reconnect'}</button><button type="button" className="secondary" disabled={busy === 'disconnect-plane'} onClick={() => disconnect('plane')}><Link2Off size={14} /> Disconnect</button></div></> : <><div className="project-settings-actions"><button type="button" disabled={busy === 'plane'} onClick={() => startOAuth('plane')}>{busy === 'plane' ? <Busy>Authorizing…</Busy> : 'Connect Plane'}</button></div><details className="project-settings-advanced"><summary>Advanced setup</summary><form onSubmit={async (event) => { event.preventDefault(); const token = event.currentTarget.token.value.trim(); if (!token) return; setBusy('plane-pat'); try { const result = await apiJson('/api/integrations/plane/connect', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ token }) }); setIntegrations((current) => ({ ...current, plane: result.integration })); event.currentTarget.reset(); setMessage('Plane connected with a Personal Access Token. Select a workspace and project to finish setup.'); } catch (connectError) { setError(connectError.message); } finally { setBusy(''); } }} className="project-settings-form"><label>Personal Access Token<input name="token" type="password" autoComplete="off" placeholder="Only use if OAuth is unavailable" /></label><button type="submit" disabled={busy === 'plane-pat'}>{busy === 'plane-pat' ? <Busy>Validating…</Busy> : 'Connect with Personal Access Token'}</button></form></details></>}
    </section>
    <section className="project-integration-card"><div className="project-integration-card-header"><div><h2>Discord</h2><p>Connect Discord to receive project notifications.</p></div><StatusBadge integration={discord} provider="discord" /></div>
      {!discord.connected ? <div className="project-settings-actions"><button type="button" disabled={busy === 'discord'} onClick={() => startOAuth('discord')}>{busy === 'discord' ? <Busy>Authorizing…</Busy> : 'Connect Discord'}</button></div> : discord.guildId && discord.channelId ? <><div className="project-integration-meta">Server: {discord.metadata?.guildName || 'Selected server'} · Channel: #{discord.metadata?.channelName || 'Selected channel'}</div><div className="project-settings-actions"><button type="button" onClick={() => { setGuildId(''); setChannelId(''); setIntegrations((current) => ({ ...current, discord: { ...current.discord, guildId: null, channelId: null } })); }}>Change destination</button><button type="button" className="secondary" disabled={busy === 'disconnect-discord'} onClick={() => disconnect('discord')}><Link2Off size={14} /> Disconnect</button></div></> : <form onSubmit={saveDestination} className="project-settings-form"><label>Server<select value={guildId} onChange={(event) => { setGuildId(event.target.value); setChannelId(''); }}><option value="">Select a server</option>{guilds.map((guild) => <option key={guild.id} value={guild.id}>{guild.name}</option>)}</select></label><label>Notification channel<select value={channelId} onChange={(event) => setChannelId(event.target.value)} disabled={!guildId}><option value="">Select a channel</option>{channels.map((channel) => <option key={channel.id} value={channel.id}>#{channel.name}</option>)}</select></label><button type="submit" disabled={busy === 'destination' || !guildId || !channelId}>{busy === 'destination' ? <Busy>Saving…</Busy> : 'Save destination'}</button><button type="button" className="secondary" onClick={() => disconnect('discord')}>Disconnect</button></form>}
    </section>
    <section className="project-integration-card"><div className="project-integration-card-header"><div><h2>HRM account links</h2><p>Select a trusted Chat account and an employee in your company. HRM verifies administrator permission and company scope.</p></div></div>
      {!hrmOptions ? <div className="project-settings-actions"><button type="button" disabled={busy === 'hrm-options'} onClick={loadHrmOptions}>{busy === 'hrm-options' ? <Busy>Loading accountsâ€¦</Busy> : 'Manage HRM links'}</button></div> : <form onSubmit={saveHrmLink} className="project-settings-form"><label>Chat user<select value={chatUserId} onChange={(event) => { const userId = event.target.value; setChatUserId(userId); const link = hrmOptions.links?.find((item) => item.userId === userId); setHrmEmployeeId(link?.employeeId || ''); }}><option value="">Select a Chat user</option>{hrmOptions.users.map((user) => <option key={user.id} value={user.id}>{user.name || user.email} {user.email ? `(${user.email})` : ''}</option>)}</select></label><label>Employee<select value={hrmEmployeeId} onChange={(event) => setHrmEmployeeId(event.target.value)} disabled={!chatUserId}><option value="">Select an employee</option>{hrmOptions.employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.displayName} â€” {employee.title}</option>)}</select></label>{selectedLink && <p className="project-current-link">Current mapping: {selectedLink.employeeId}. Saving replaces it.</p>}<div className="project-settings-actions"><button type="submit" disabled={busy === 'hrm-link' || !chatUserId || !hrmEmployeeId}>{busy === 'hrm-link' ? <Busy>Savingâ€¦</Busy> : selectedLink ? 'Replace link' : 'Link account'}</button>{selectedLink && <button type="button" className="secondary" disabled={busy === 'hrm-unlink'} onClick={disconnectHrmLink}>{busy === 'hrm-unlink' ? <Busy>Disconnectingâ€¦</Busy> : 'Disconnect'}</button>}</div></form>}
    </section>
  </div></div>;
}
