import { ChevronDown, Mic, Paperclip, Send, Settings2, Square } from 'lucide-react';
import { useState } from 'react';
import ContextWindow from './ContextWindow';

export default function ChatComposer({ value, setValue, onSend, isSending, servers, selectedServers, onToggleServer, placeholder, contextUsage }) {
  const [open, setOpen] = useState(false);
  const [contextOpen, setContextOpen] = useState(false);
  return <form className="project-composer" onSubmit={onSend}><textarea value={value} onChange={(event) => setValue(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); event.currentTarget.form?.requestSubmit(); } }} placeholder={placeholder} rows={1} aria-label="Tin nhắn" /><div className="project-compose-row"><button type="button" className="composer-icon" title="Đính kèm" aria-label="Đính kèm"><Paperclip size={19} /></button><button type="button" className="composer-icon" title="Tùy chọn" aria-label="Tùy chọn"><Settings2 size={18} /></button><ContextWindow usage={contextUsage} open={contextOpen} onToggle={() => setContextOpen((current) => !current)} /><div className="mcp-selector-wrap"><button type="button" className="composer-mcp" onClick={() => setOpen((current) => !current)} aria-expanded={open}><span className="mcp-selector-mark">⌁</span>{selectedServers.length ? `${selectedServers.length} selected` : 'Chọn MCP'}<ChevronDown size={14} /></button>{open && <div className="mcp-popover">{servers.map((server) => <label key={server.name}><input type="checkbox" checked={selectedServers.includes(server.name)} onChange={() => onToggleServer(server.name)} /><span>{server.label || server.name}</span></label>)}</div>}</div><span className="composer-hint">{selectedServers.length ? 'MCP được phép dùng trong tin nhắn này' : 'Chưa chọn MCP server'}</span><button type="button" className="composer-icon" title="Nhập bằng giọng nói" aria-label="Nhập bằng giọng nói"><Mic size={19} /></button><button className="send-button" type="submit" disabled={!isSending && !value.trim()} title={isSending ? 'Đang tạo câu trả lời' : 'Gửi'} aria-label={isSending ? 'Đang tạo câu trả lời' : 'Gửi'}>{isSending ? <Square size={14} fill="currentColor" /> : <Send size={16} />}</button></div></form>;
}
