import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';

const SUPPORTED_PROVIDERS = new Set(['plane', 'discord']);
const STORE_VERSION = 1;
function assertProvider(provider) { if (typeof provider !== 'string' || !SUPPORTED_PROVIDERS.has(provider)) throw new Error(`Unsupported integration provider: ${provider}`); }
function assertUserId(userId) { if (userId == null || String(userId).trim() === '') throw new Error('Authenticated user is required'); return String(userId); }
function keyBuffer(value) { if (Buffer.isBuffer(value) && value.length === 32) return value; if (typeof value === 'string' && /^[0-9a-f]{64}$/i.test(value)) return Buffer.from(value, 'hex'); throw new Error('INTEGRATION_ENCRYPTION_KEY must be a 64-character hexadecimal value'); }
function encrypt(value, key) { if (value == null || value === '') return null; const iv = crypto.randomBytes(12); const cipher = crypto.createCipheriv('aes-256-gcm', key, iv); const ciphertext = Buffer.concat([cipher.update(String(value), 'utf8'), cipher.final()]); return `v1:${iv.toString('base64url')}:${ciphertext.toString('base64url')}:${cipher.getAuthTag().toString('base64url')}`; }
function decrypt(value, key) { if (!value) return null; const [version, ivText, ciphertextText, tagText] = String(value).split(':'); if (version !== 'v1' || !ivText || !ciphertextText || !tagText) throw new Error('Invalid encrypted integration credential'); const decipher = crypto.createDecipheriv('aes-256-gcm', key, Buffer.from(ivText, 'base64url')); decipher.setAuthTag(Buffer.from(tagText, 'base64url')); return Buffer.concat([decipher.update(Buffer.from(ciphertextText, 'base64url')), decipher.final()]).toString('utf8'); }
function safeIntegration(integration) { return { id: integration.id, provider: integration.provider, connected: true, externalUserId: integration.externalUserId ?? null, expiresAt: integration.expiresAt ?? null, credentialType: integration.credentialType ?? null, workspaceId: integration.workspaceId ?? null, workspaceSlug: integration.workspaceSlug ?? null, guildId: integration.guildId ?? null, channelId: integration.channelId ?? null, metadata: integration.metadata ?? {}, createdAt: integration.createdAt, updatedAt: integration.updatedAt }; }
function safeMetadata(metadata) { if (metadata == null) return {}; if (typeof metadata !== 'object' || Array.isArray(metadata)) throw new Error('metadata must be an object'); const inspect = (value) => { if (value == null || typeof value !== 'object') return; if (Array.isArray(value)) return value.forEach(inspect); for (const [key, nestedValue] of Object.entries(value)) { if (/(token|secret|password|authorization|credential|private.?key)/i.test(key)) throw new Error(`metadata field is not allowed: ${key}`); inspect(nestedValue); } }; inspect(metadata); return metadata; }

export class IntegrationService {
  constructor({ integrationRepository, filePath, encryptionKey } = {}) { this.integrationRepository = integrationRepository; this.filePath = filePath; this.encryptionKey = encryptionKey ? keyBuffer(encryptionKey) : null; this.writeQueue = Promise.resolve(); if (!this.integrationRepository && !this.filePath) throw new Error('IntegrationService requires PostgreSQL repository'); }
  requireEncryptionKey() { if (!this.encryptionKey) throw new Error('INTEGRATION_ENCRYPTION_KEY is required to store integration credentials'); return this.encryptionKey; }
  async readStore() { try { const parsed = JSON.parse(await fs.readFile(this.filePath, 'utf8')); if (!parsed || parsed.schemaVersion !== STORE_VERSION || !Array.isArray(parsed.integrations)) throw new Error('Invalid integration store'); return parsed; } catch (error) { if (error.code === 'ENOENT') return { schemaVersion: STORE_VERSION, integrations: [] }; throw error; } }
  async writeStore(store) { await fs.mkdir(path.dirname(this.filePath), { recursive: true }); const temporaryPath = `${this.filePath}.${process.pid}.tmp`; await fs.writeFile(temporaryPath, JSON.stringify(store, null, 2), { encoding: 'utf8', mode: 0o600 }); await fs.rename(temporaryPath, this.filePath); }
  async updateStore(mutator) { const operation = this.writeQueue.then(async () => { const store = await this.readStore(); const value = await mutator(store); await this.writeStore(store); return value; }); this.writeQueue = operation.catch(() => {}); return operation; }
  decodeRecord(row) { const encrypted = row.encryptedCredentials ?? row; const key = (encrypted.accessTokenEncrypted || encrypted.refreshTokenEncrypted) ? this.requireEncryptionKey() : null; return { id: row.id, userId: row.userId ?? row.user_id, provider: row.provider, ...encrypted, accessToken: decrypt(encrypted.accessTokenEncrypted, key), refreshToken: decrypt(encrypted.refreshTokenEncrypted, key), createdAt: row.createdAt ?? row.created_at, updatedAt: row.updatedAt ?? row.updated_at }; }
  async getIntegration(userId, provider) { const ownerId = assertUserId(userId); assertProvider(provider); if (this.integrationRepository) { const row = await this.integrationRepository.getIntegration(ownerId, provider); return row ? this.decodeRecord(row) : null; } const store = await this.readStore(); const item = store.integrations.find((entry) => entry.userId === ownerId && entry.provider === provider); return item ? this.decodeRecord(item) : null; }
  async saveIntegration(userId, provider, credentialData = {}, { allowCredentialless = false } = {}) { const ownerId = assertUserId(userId); assertProvider(provider); const key = this.requireEncryptionKey(); const existing = await this.getIntegration(ownerId, provider); const encryptedCredentials = { externalUserId: credentialData.externalUserId ?? existing?.externalUserId ?? null, credentialType: credentialData.credentialType ?? existing?.credentialType ?? null, accessTokenEncrypted: encrypt(credentialData.accessToken, key) ?? existing?.accessTokenEncrypted ?? null, refreshTokenEncrypted: encrypt(credentialData.refreshToken, key) ?? existing?.refreshTokenEncrypted ?? null, expiresAt: credentialData.expiresAt ?? existing?.expiresAt ?? null, workspaceId: credentialData.workspaceId ?? existing?.workspaceId ?? null, workspaceSlug: credentialData.workspaceSlug ?? existing?.workspaceSlug ?? null, guildId: credentialData.guildId ?? existing?.guildId ?? null, channelId: credentialData.channelId ?? existing?.channelId ?? null, metadata: credentialData.metadata === undefined ? (existing?.metadata ?? {}) : safeMetadata(credentialData.metadata) }; if (!encryptedCredentials.accessTokenEncrypted && !encryptedCredentials.refreshTokenEncrypted && !existing && !allowCredentialless) throw new Error('At least one credential is required'); if (this.integrationRepository) { const row = await this.integrationRepository.upsertIntegration(ownerId, provider, encryptedCredentials); return safeIntegration(this.decodeRecord(row)); } const now = new Date().toISOString(); return this.updateStore(async (store) => { const record = { id: existing?.id ?? crypto.randomUUID(), userId: ownerId, provider, ...encryptedCredentials, createdAt: existing?.createdAt ?? now, updatedAt: now }; const index = store.integrations.findIndex((entry) => entry.userId === ownerId && entry.provider === provider); if (index >= 0) store.integrations[index] = record; else store.integrations.push(record); return safeIntegration(this.decodeRecord(record)); }); }
  async disconnectIntegration(userId, provider) { const ownerId = assertUserId(userId); assertProvider(provider); if (this.integrationRepository) return this.integrationRepository.deleteIntegration(ownerId, provider); return this.updateStore(async (store) => { const before = store.integrations.length; store.integrations = store.integrations.filter((entry) => !(entry.userId === ownerId && entry.provider === provider)); return before !== store.integrations.length; }); }
  async hasIntegration(userId, provider) { return Boolean(await this.getIntegration(userId, provider)); }
  async getSafeIntegration(userId, provider) { const integration = await this.getIntegration(userId, provider); return integration ? safeIntegration(integration) : { provider, connected: false }; }
}

export { safeIntegration, encrypt, decrypt, keyBuffer };
